name: OCI ARM Grabber

on:
  workflow_dispatch: # This adds a "Run" button for you
  schedule:
    - cron: '*/5 * * * *' # This tries every 5 minutes automatically

jobs:
  grab-instance:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: Install Dependencies
        run: composer install

      - name: Run Script
        env:
          OCI_REGION: ${{ secrets.OCI_REGION }}
          OCI_USER_ID: ${{ secrets.OCI_USER_ID }}
          OCI_TENANCY_ID: ${{ secrets.OCI_TENANCY_ID }}
          OCI_KEY_FINGERPRINT: ${{ secrets.OCI_FINGERPRINT }}
          OCI_PRIVATE_KEY: ${{ secrets.OCI_PRIVATE_KEY }}
          OCI_SUBNET_ID: ${{ secrets.OCI_SUBNET_ID }}
          OCI_SSH_PUBLIC_KEY: ${{ secrets.OCI_SSH_PUBLIC_KEY }}
          # Use the OCID for Ubuntu 22.04 ARM in Hyderabad
          OCI_IMAGE_ID: 'ocid1.image.oc1.ap-hyderabad-1.aaaaaaaakw5v...' 
        run: php index.php